name: expenses_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  pinput: ^5.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/logos/

fonts:
  - family: ClashGrotesk
    fonts:
      - asset: assets/fonts/ClashGrotesk-Light.otf
        weight: 300
        style: normal
      - asset: assets/fonts/ClashGrotesk-Extralight.otf
        weight: 200
        style: normal
      - asset: assets/fonts/ClashGrotesk-Regular.otf
        weight: 400
        style: normal
      - asset: assets/fonts/ClashGrotesk-Medium.otf
        weight: 500
        style: medium
      - asset: assets/fonts/ClashGrotesk-Semibold.otf
        weight: 600
        style: normal

